---
platform: linux 
image_resource: 
  type: docker-image
  source: 
    repository: havener/build-environment
    tag: latest
inputs: 
- name: release 
- name: s3.fissile-linux
- name: ci 
- name: s3.stemcell-version
params: 
  STEMCELL_REPOSITORY: 
  STEMCELL_VERSION: 
  RELEASE_NAME: 
  DOCKER_TEAM_USERNAME: 
  DOCKER_TEAM_PASSWORD_RW: 
  REGISTRY_NAMESPACE: 
run: 
  path: ci/pipelines/release-non-bosh-images/tasks/build.sh
