# This pipeline will setup the build for all the cf_deployment_releases specified below.

resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: ci
  type: git
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
- name: docker-image-resource
  type: git
  source:
    uri: ((docker-image-resource-repo))
    branch: ((docker-image-resource-branch))
- name: cf-deployment-v12.33.0
  type: git
  source:
    uri: ((cf-deployment-repo))
    branch: ((cf-deployment-branch))
    tag_filter: v12.33.0
- name: s3.fissile-linux
  type: file-url
  source:
    url: https://cf-opensusefs2.s3.amazonaws.com/fissile/develop/fissile-7.0.0%2B374.gb8e8e6af.linux-amd64.tgz
    filename: fissile.tgz
    skip-ssl-verification: true    

jobs:
  - name: build-v12.33.0-uaa
    plan:
    - in_parallel:
      - get: ci
      - get: docker-image-resource
      - get: cf-deployment-v12.33.0
      - get: s3.fissile-linux
    - do:
      - task: build
        privileged: true
        timeout: 1h30m
        input_mapping:
          s3.stemcell-version: s3.fissile-stemcell-version
          cf-deployment: cf-deployment-v12.33.0
        params:
          STEMCELL_OS: ((stemcell-os))
          STEMCELL_REPOSITORY: ((stemcell-repository))
          STEMCELL_VERSIONED_FILE: ((stemcell-version-file))
          CF_DEPLOYMENT_YAML: ((cf-deployment-yaml))
          RELEASE: uaa
          DOCKER_REGISTRY: ((docker-registry))
          DOCKER_ORGANIZATION: ((docker-organization))
          DOCKER_TEAM_USERNAME: ((dockerhub-username))
          DOCKER_TEAM_PASSWORD_RW: ((dockerhub-password))
          STEMCELL_VERSION: ((stemcell-version)) 
        file: ci/pipelines/release-cf-deployment-images/tasks/build.yml
