# This pipeline will setup the build for all the cf_deployment_releases specified below.


resources:
- name: ci
  type: git
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
- name: docker-image-resource
  type: git
  source:
    uri: ((docker-image-resource-repo))
    branch: ((docker-image-resource-branch))
- name: cf-deployment-v12.18.0
  type: git
  source:
    uri: ((cf-deployment-repo))
    branch: ((cf-deployment-branch))
    tag_filter: v.12.18.0
- name: s3.fissile-linux
  type: file-url
  source:
    url: https://www.dropbox.com/s/eu6h50r86pkgia4/fissile-4.3.tar.gz?dl=0
    filename: fissile-4.3.tar.gz
    skip-ssl-verification: true    

jobs:
  - name: build-v12.18.0-uaa
    plan:
    - in_parallel:
      - get: ci
      - get: docker-image-resource
      - get: cf-deployment-v12.18.0
      - get: s3.fissile-linux
    - do:
      - task: build
        privileged: true
        timeout: 1h30m
        input_mapping:
          s3.stemcell-version: s3.fissile-stemcell-version
          cf-deployment: cf-deployment-v12.18.0
        params:
          GOPROXY: ((goproxy))
          STEMCELL_OS: ((stemcell-os))
          STEMCELL_REPOSITORY: ((stemcell-repository))
          STEMCELL_VERSIONED_FILE: ((stemcell-version-file))
          CF_DEPLOYMENT_YAML: ((cf-deployment-yaml))
          RELEASE: uaa
          DOCKER_REGISTRY: ((docker-registry))
          DOCKER_ORGANIZATION: ((docker-organization))
          DOCKER_TEAM_USERNAME: ((dockerhub.username))
          DOCKER_TEAM_PASSWORD_RW: ((dockerhub.password))
          STEMCELL_VERSION: ((stemcell-version)) 
        file: ci/pipelines/release-cf-deployment-images/tasks/build.yml
