---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfcontainerization/base-ci
    tag: latest
inputs:
- name: ci
- name: docker-image-resource
- name: cf-deployment
- name: s3.fissile-linux
params:
  STEMCELL_OS:
  STEMCELL_REPOSITORY:
  CF_DEPLOYMENT_YAML:
  RELEASE:
  DOCKER_ORGANIZATION:
  DOCKER_TEAM_USERNAME:
  DOCKER_TEAM_PASSWORD_RW:
  STEMCELL_VERSION:
run:
  path: ci/pipelines/release-images-cf-deployment/tasks/build.sh
