---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfcontainerization/base-ci
    tag: latest
inputs:
- name: cf-deployment
- name: ci
params:
  CF_DEPLOYMENT_YAML:
  RELEASES:
run:
  path: ci/pipelines/release-images-cf-deployment/tasks/prepare_build.sh
