resource_types: 
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources: 
- name: ci 
  type: git 
  source: 
    uri: ((ci-repo))
    branch: ((ci-branch)) 

    #- name: pxc-release
    #type: bosh-io-release
    #source: 
    #repository: cloudfoundry-incubator/pxc-release
    #regexp: ((pxc-release-version))

- name: eirini-release
  type: bosh-io-release
  source:
    respository: cloudfoundry-incubator/eirini-release
    regex: ((eirini-release-version)) 

- name: bits-service-release
  type: bosh-io-release
  source:
    respository: cloudfoundry-incubator/bits-service-release
    regex: ((eirini-release-version)) 

- name: app-autoscaler-release
  type: bosh-io-release
  source:
    respository: cloudfoundry/app-autoscaler-release
    regex: ((app-autoscaler-release-version)) 

- name: s3.fissile-linux
  type: file-url
  source:
    url: https://cf-opensusefs2.s3.amazonaws.com/fissile/develop/fissile-7.0.0%2B374.gb8e8e6af.linux-amd64.tgz
    filename: fissile.tgz
    skip-ssl-verification: true

jobs: 
  - name: build-eirini-release-((eirini-release-version)) 
    plan: 
    - in_parallel: 
      - get: ci 
      - get: s3.fissile-linux
      - get: eirini-release
        params: 
          tarball: false 
    - do:
      - task: build 
        privileged: true 
        timeout: 1h30m 
        input_mapping:
          release: eirini-release
        params:
          STEMCELL_REPOSITORY: ((stemcell-repository))
          STEMCELL_VERSION: ((stemcell-version)) 
          RELEASE_NAME: eirini
          DOCKER_TEAM_USERNAME: ((dockerhub-username))
          DOCKER_TEAM_PASSWORD_RW: ((dockerhub-password))
          REGISTRY_NAMESPACE: ((docker-organization))  
        file: ci/pipelines/release-non-bosh-image/tasks/build.yml

  - name: build-app-autoscaler-release-((app-autoscaler-release-version)) 
    plan: 
    - in_parallel: 
      - get: ci 
      - get: s3.fissile-linux
      - get: app-autoscaler-release
        params: 
          tarball: false 
    - do:
      - task: build 
        privileged: true 
        timeout: 1h30m 
        input_mapping:
          release: app-autoscaler-release
        params:
          STEMCELL_REPOSITORY: ((stemcell-repository))
          STEMCELL_VERSION: ((stemcell-version)) 
          RELEASE_NAME: app-autoscaler
          DOCKER_TEAM_USERNAME: ((dockerhub-username))
          DOCKER_TEAM_PASSWORD_RW: ((dockerhub-password))
          REGISTRY_NAMESPACE: ((docker-organization))  
        file: ci/pipelines/release-non-bosh-image/tasks/build.yml

  - name: build-bits-service-release-((bits-service-release-version)) 
    plan: 
    - in_parallel: 
      - get: ci 
      - get: s3.fissile-linux
      - get: bits-service-release
        params: 
          tarball: false 
    - do:
      - task: build 
        privileged: true 
        timeout: 1h30m 
        input_mapping:
          release: bits-service-release
        params:
          STEMCELL_REPOSITORY: ((stemcell-repository))
          STEMCELL_VERSION: ((stemcell-version)) 
          RELEASE_NAME: bits-service
          DOCKER_TEAM_USERNAME: ((dockerhub-username))
          DOCKER_TEAM_PASSWORD_RW: ((dockerhub-password))
          REGISTRY_NAMESPACE: ((docker-organization))  
        file: ci/pipelines/release-non-bosh-image/tasks/build.yml

